export const NEW_MESSAGE = 'NEW_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const JOIN_TEAM = 'JOIN_TEAM';
export const LEAVE_TEAM = 'LEAVE_TEAM';
export const TEAM_NOTIFICATION = 'TEAM_NOTIFICATION';
export const CHANNEL_ADDED = 'CHANNEL_ADDED';